### PR TITLE
Improved a few files imo, need feedback on tone of voice in a few places

### PR DESCRIPTION
**Pull request by that-audio-guy**
Need more input on the tone of voice and personas tbh. Do you want me to create a document that I'll base everything from for this?

Steve

### CODE REVIEW

**Comment by benbowler** [comment]
Amazing thanks Steve. Will have a read.

**Comment by benbowler** [comment]
We don't have a tone of voice doc? Should/could that exist and in what form. Thoughts @fatkidonfire

**Comment by fatkidonfire** [comment]
We haven't yet got one so what you see now is basically what we've got. 

We want this to be accessible and clear/ concise - but could argue we want it to be fairly formal given we can use it as a marketing tool?

**Comment by that-audio-guy** [comment]
I'll pull a basic tone of voice guide together tomorrow for you to fill in the blanks. It's a great exercise to do anyhow and really helps shape the message for everything.

:)

Steve

**Comment by benbowler** [comment]
Yeah I'm super into that.

**Comment by fatkidonfire** [comment]
<3 go team!

**Pull request closed without merging**
